title:              TRAVEL
email:              2011463@gmail.com
description:        VI VU CÙNG TÔI
author:             Huynh Minh Tuyen
baseurl:            
url:                "https://abcxyzzzzzz.github.io"

# Social Profiles
twitter_username:   
github_username:    abcxyzzzzzz
facebook_username:  tuyen02x
instagram_username:  tuyen02x
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           4
paginate_path:      "/posts/page:4/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-cayman
